### ISSUE TITLE
服务端代码运行起来之后访问不了

### ISSUE THREAD

**Issue by Maybe4U** [DiscoverForever/learn_flutter#1]
哥，按照你服务端的代码运行起来之后，求指导！！！
Error: Not Found
    at E:\Other\flutter_mock_server\app.js:31:13
    at Layer.handle [as handle_request] (E:\Other\flutter_mock_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:317:13)
    at E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:275:10)
    at E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:635:15
    at next (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:47:12)

**Comment by juedishu** [comment]
同样的，Welcome to Express，localhost可以访问，接口访问就404😄

**Comment by juedishu** [comment]
> 哥，按照你服务端的代码运行起来之后，求指导！！！
> Error: Not Found
> at E:\Other\flutter_mock_server\app.js:31:13
> at Layer.handle [as handle_request] (E:\Other\flutter_mock_server\node_modules\express\lib\router\layer.js:95:5)
> at trim_prefix (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:317:13)
> at E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:284:7
> at Function.process_params (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:335:12)
> at next (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:275:10)
> at E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:635:15
> at next (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:260:14)
> at Function.handle (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:174:3)
> at router (E:\Other\flutter_mock_server\node_modules\express\lib\router\index.js:47:12)
把baseurl改为自己本机ip或者把模拟器的映射地址，用ipv4地址就可以了。

**Comment by DiscoverForever** [comment]
真机运行的话 lib/api/api.dart中的baseUrl需要修改为你的本机ip
